# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-22 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_reviewer_app', '0002_reviewmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewManager',
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='belt_reviewer_app.Book'),
        ),
    ]
