-- MySQL Script generated by MySQL Workbench
-- Mon Feb 12 13:01:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema belts
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `belts` ;

-- -----------------------------------------------------
-- Schema belts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `belts` DEFAULT CHARACTER SET utf8 ;
USE `belts` ;

-- -----------------------------------------------------
-- Table `belts`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `belts`.`students` ;

CREATE TABLE IF NOT EXISTS `belts`.`students` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `belts`.`belts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `belts`.`belts` ;

CREATE TABLE IF NOT EXISTS `belts`.`belts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(12) NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `belts`.`student_belts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `belts`.`student_belts` ;

CREATE TABLE IF NOT EXISTS `belts`.`student_belts` (
  `id` INT NOT NULL,
  `student_id` INT NULL,
  `belt_id` INT NULL,
  `earned_on` DATETIME NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `student_belts_student_id_idx` (`student_id` ASC),
  INDEX `student_belts_belt_id_idx` (`belt_id` ASC),
  CONSTRAINT `student_belts_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `belts`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student_belts_belt_id`
    FOREIGN KEY (`belt_id`)
    REFERENCES `belts`.`belts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
