-- MySQL Script generated by MySQL Workbench
-- Mon Feb 12 13:19:16 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blogs
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `blogs` ;

-- -----------------------------------------------------
-- Schema blogs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blogs` DEFAULT CHARACTER SET utf8 ;
USE `blogs` ;

-- -----------------------------------------------------
-- Table `blogs`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogs`.`users` ;

CREATE TABLE IF NOT EXISTS `blogs`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogs`.`blogs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogs`.`blogs` ;

CREATE TABLE IF NOT EXISTS `blogs`.`blogs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` LONGTEXT NULL,
  `user_id` INT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  INDEX `user_id_idx` (`user_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `blogs_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `blogs`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogs`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogs`.`posts` ;

CREATE TABLE IF NOT EXISTS `blogs`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` LONGTEXT NULL,
  `user_id` INT NULL,
  `blog_id` INT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `post_id_idx` (`blog_id` ASC),
  CONSTRAINT `posts_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `blogs`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `posts_blog_id`
    FOREIGN KEY (`blog_id`)
    REFERENCES `blogs`.`blogs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogs`.`logins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogs`.`logins` ;

CREATE TABLE IF NOT EXISTS `blogs`.`logins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `logged_in` DATETIME NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `logins_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `blogs`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogs`.`blog_administrators`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogs`.`blog_administrators` ;

CREATE TABLE IF NOT EXISTS `blogs`.`blog_administrators` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `blog_id` INT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `blog_admin_user_id_idx` (`user_id` ASC),
  INDEX `blog_admin_blog_id_idx` (`blog_id` ASC),
  CONSTRAINT `blog_admin_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `blogs`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `blog_admin_blog_id`
    FOREIGN KEY (`blog_id`)
    REFERENCES `blogs`.`blogs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogs`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogs`.`comments` ;

CREATE TABLE IF NOT EXISTS `blogs`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT NULL,
  `user_id` INT NULL,
  `commented_on` DATETIME NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `comments_post_id_idx` (`post_id` ASC),
  INDEX `comments_user_id_idx` (`user_id` ASC),
  CONSTRAINT `comments_post_id`
    FOREIGN KEY (`post_id`)
    REFERENCES `blogs`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comments_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `blogs`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogs`.`post_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogs`.`post_files` ;

CREATE TABLE IF NOT EXISTS `blogs`.`post_files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `post_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `post_files_post_id_idx` (`post_id` ASC),
  CONSTRAINT `post_files_post_id`
    FOREIGN KEY (`post_id`)
    REFERENCES `blogs`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogs`.`pages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogs`.`pages` ;

CREATE TABLE IF NOT EXISTS `blogs`.`pages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogs`.`browsing_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogs`.`browsing_history` ;

CREATE TABLE IF NOT EXISTS `blogs`.`browsing_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `page_id` INT NULL,
  `time_arrived` DATETIME NULL,
  `time_left` VARCHAR(45) NULL,
  `ip_address` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `browsing_history_page_id_idx` (`page_id` ASC),
  INDEX `browsing_history_user_id_idx` (`user_id` ASC),
  CONSTRAINT `browsing_history_page_id`
    FOREIGN KEY (`page_id`)
    REFERENCES `blogs`.`pages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `browsing_history_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `blogs`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
