-- MySQL Script generated by MySQL Workbench
-- Mon Feb 12 12:15:08 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema likes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `likes` ;

-- -----------------------------------------------------
-- Schema likes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `likes` DEFAULT CHARACTER SET utf8 ;
USE `likes` ;

-- -----------------------------------------------------
-- Table `likes`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `likes`.`users` ;

CREATE TABLE IF NOT EXISTS `likes`.`users` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `image_id` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `likes`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `likes`.`posts` ;

CREATE TABLE IF NOT EXISTS `likes`.`posts` (
  `id` INT NOT NULL,
  `text` LONGTEXT NULL,
  `user_id` INT NULL,
  `posted_at` DATETIME NULL,
  `original_post_id` INT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `posts_user_id_idx` (`user_id` ASC),
  INDEX `share_post_id_idx` (`original_post_id` ASC),
  CONSTRAINT `posts_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `likes`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `share_post_id`
    FOREIGN KEY (`original_post_id`)
    REFERENCES `likes`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `likes`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `likes`.`images` ;

CREATE TABLE IF NOT EXISTS `likes`.`images` (
  `id` INT NOT NULL,
  `location` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `likes`.`post_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `likes`.`post_images` ;

CREATE TABLE IF NOT EXISTS `likes`.`post_images` (
  `id` INT NOT NULL,
  `post_id` INT NULL,
  `image_id` INT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `post_images_image_id_idx` (`image_id` ASC),
  INDEX `post_images_post_id_idx` (`post_id` ASC),
  CONSTRAINT `post_images_image_id`
    FOREIGN KEY (`image_id`)
    REFERENCES `likes`.`images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `post_images_post_id`
    FOREIGN KEY (`post_id`)
    REFERENCES `likes`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `likes`.`likes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `likes`.`likes` ;

CREATE TABLE IF NOT EXISTS `likes`.`likes` (
  `id` INT NOT NULL,
  `user_id` INT NULL,
  `post_id` INT NULL,
  `created` DATETIME NULL,
  `updated` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `likes_user_id_idx` (`user_id` ASC),
  INDEX `likes_post_id_idx` (`post_id` ASC),
  CONSTRAINT `likes_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `likes`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `likes_post_id`
    FOREIGN KEY (`post_id`)
    REFERENCES `likes`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `likes`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `likes`.`comments` ;

CREATE TABLE IF NOT EXISTS `likes`.`comments` (
  `id` INT NOT NULL,
  `user_id` INT NULL,
  `comment` VARCHAR(45) NULL,
  `posted_at` DATETIME NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `post_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `comments_post_id_idx` (`post_id` ASC),
  INDEX `comments_user_id_idx` (`user_id` ASC),
  CONSTRAINT `comments_post_id`
    FOREIGN KEY (`post_id`)
    REFERENCES `likes`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comments_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `likes`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
