-- MySQL Script generated by MySQL Workbench
-- Mon Feb 12 12:48:20 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema likes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `likes` ;

-- -----------------------------------------------------
-- Schema likes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `likes` DEFAULT CHARACTER SET utf8 ;
USE `likes` ;

-- -----------------------------------------------------
-- Table `likes`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `likes`.`users` ;

CREATE TABLE IF NOT EXISTS `likes`.`users` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `image_id` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `likes`.`restaurants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `likes`.`restaurants` ;

CREATE TABLE IF NOT EXISTS `likes`.`restaurants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `likes`.`reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `likes`.`reviews` ;

CREATE TABLE IF NOT EXISTS `likes`.`reviews` (
  `id` INT NOT NULL,
  `text` LONGTEXT NULL,
  `user_id` INT NULL,
  `restaurant_id` INT NULL,
  `stars` TINYINT(5) NULL,
  `posted_at` DATETIME NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `reviews_restaurant_id_idx` (`restaurant_id` ASC),
  INDEX `reviews_user_id_idx` (`user_id` ASC),
  CONSTRAINT `reviews_restaurant_id`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `likes`.`restaurants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reviews_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `likes`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
